AllCops:
  DisplayCopNames:    true
  DisplayStyleGuide:  true
  StyleGuideCopsOnly: true
  TargetRubyVersion:  2.3

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

Style/FileName:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - spec/**/*_spec.rb